["protostar.config"]
protostar_version = "0.3.2"

["protostar.project"]
libs_path = "lib"

["protostar.build"]
output = "./starknet-artifacts/protostar"

["protostar.contracts"]
main = [
    "./contracts/library/rewards.cairo",
]

test = [
    "./contracts/test/rewards_test.cairo",
]

["protostar.test"]
cairo-path = [
    "./protostar-test/"
]