["protostar.config"]
protostar_version = "0.4.2"

["protostar.project"]
libs_path = "lib"

["protostar.shared_command_configs"]
cairo-path = ["./lib/cairo_contracts_git/src", "./lib/cairo_math_64x61_git/contracts"]

["protostar.build"]
output = "./starknet-artifacts/protostar"

["protostar.contracts"]
exchange=[
    "./contracts/perpx_v1_exchange.cairo",
]

["protostar.test"]
cairo-path = [
    "./protostar-test/",
    "./lib/cairo_contracts_git/src"
]
ignore = [
    "starknet-artifacts"
]