["protostar.config"]
protostar_version = "0.3.2"

["protostar.project"]
libs_path = "lib"

["protostar.build"]
output = "./starknet-artifacts/protostar"

["protostar.contracts"]
exchange=[
    "./contracts/perpx_v1_exchange.cairo",
]
exchange_test = [
    "./contracts/test/perpx_v1_exchange_test.cairo",
]
vault_test = [
    "./contracts/test/vault_test.cairo",
]

["protostar.test"]
cairo-path = [
    "./protostar-test/"
]
ignore = [
    "starknet-artifacts"
]