[project]
protostar-version = "0.7.0"
lib-path = "lib"
cairo-path = ["./lib/cairo_contracts_git/src", "./lib/cairo_math_64x61_git/contracts"]

[contracts]
exchange = ["contracts/perpx_v1_exchange.cairo"]

[build]
output = "./starknet-artifacts/protostar"

[test]
cairo-path = ["./protostar-test/", "./lib/cairo_contracts_git/src"]
ignore = ["starknet-artifacts"]

